### ISSUE TITLE
can iphub API be added?

### ISSUE THREAD

**Issue by eemmbb** [danielepantaleone/b3-plugin-proxyfilter#1]
Hi, it looks like the winmxunlimited api has been discontinued a while back, could it be possible to add iphub.info API into this plugin? It offers both free and paid proxy detection.

For reference here is a plugin made using the api provided by iphub, but I would like to use it with this plugin since it doesn't require IPy:  https://github.com/pedrxd/b3-plugin-vpnblocker

Thanks!

**Comment by danielepantaleone** [comment]
Hello. I do not have time to maintain this plugin anymore, but feel free so send a pull request with the additional code.
